### ISSUE TITLE
Trying to untar a folder

### ISSUE THREAD

**Issue by JaikrishnaTS** [GRAPLE/GRAPLEr#12]
GrapleGetExperimentResults tries to list all files inside Results directory and tries to untar and delete them. 

Probably it is meant to take only the files, but sometimes it tries to untar the Sims directory and fails with it. Log below. 

@smahesul @kcratie This was the issue I had been mentioning two weeks before.

> GrapleCheckExperimentCompletion(graplerURL, expId1)
> $curr_status
> [1] "completed"
> 
> setwd(expRootDir)
> GrapleGetExperimentResults(graplerURL, expId1)
> --2016-03-29 17:13:54--  http://10.244.37.116:5000/KF085HXATWIE8A2LGJE4ZHWVZBU1YH7X4FHLYUU9/Results/output.tar.gz
> Connecting to 10.244.37.116:5000... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 573120 (560K) [application/x-tar]
> Saving to: ‘/home/jaikrishna/work/SimRoot1/Exp1/results.tar.gz’

```
 0K .......... .......... .......... .......... ..........  8% 10.7M 0s
50K .......... .......... .......... .......... .......... 17% 7.56M 0s
```

   100K .......... .......... .......... .......... .......... 26% 10.1M 0s
   150K .......... .......... .......... .......... .......... 35% 10.7M 0s
   200K .......... .......... .......... .......... .......... 44% 10.4M 0s
   250K .......... .......... .......... .......... .......... 53% 10.7M 0s
   300K .......... .......... .......... .......... .......... 62% 10.4M 0s
   350K .......... .......... .......... .......... .......... 71% 10.4M 0s
   400K .......... .......... .......... .......... .......... 80% 10.8M 0s
   450K .......... .......... .......... .......... .......... 89% 10.4M 0s
   500K .......... .......... .......... .......... .......... 98% 10.3M 0s
   550K .........                                             100% 11.7M=0.05s

2016-03-29 17:13:54 (10.2 MB/s) - ‘/home/jaikrishna/work/SimRoot1/Exp1/results.tar.gz’ saved [573120/573120]

/bin/tar: Sims: Cannot read: Is a directory
/bin/tar: At beginning of tape, quitting now
/bin/tar: Error is not recoverable: exiting now
[1] "/home/jaikrishna/work/SimRoot1/Exp1/results.tar.gz"
Warning messages:
1: In untar(x) : ‘/bin/tar -xf 'Sims'’ returned error code 2
2: In file.remove(x) :
  cannot remove file 'Sims', reason 'Directory not empty'

**Comment by smahesul** [comment]
Why is the directory Results not created inside your experiment root directory, "/home/jaikrishna/work/SimRoot1/Exp1/Results" and if this regarding the results directory already having few files, then this is a known issue, which we will be dealing with in v 2.0..

**Comment by JaikrishnaTS** [comment]
The results directory is being created and all the files are being extracted correctly. (at least for Exp1)

The problem is trying to extract for files in the Result directory. Probably this is done during double unarchiving.

**Comment by JaikrishnaTS** [comment]
As seen from the code, the results.tar is extracted which produces a 'Sims' directory inside 'exp_root_dir/Results'. Now all files inside the Results directory are selected and untar'ed. That's where the issue is!

It also tries to extract 'Sims' directory

**Comment by smahesul** [comment]
Resolved.
